stages:
  - build
  - exec
  - run
  - test

build-job:
  stage: build
  image: rust:latest
  before_script:
    - touch builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable
    - chmod +x builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable 
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable

show-executable:
  stage: exec
  script:
    - echo " -----------------Executable-------------------------" 
    - ./builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable

run-server-job:
  stage: run
  image: rust:latest
  before_script:
    - ifconfig
    - touch test.log
  script:
    - (./test_server.sh & sleep 10 && ./test_client.sh & sleep 20) >test.log
    
  after_script:
    - echo "Output"
    - cat test.log

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test