stages:
  - build
  - exec
  - run
  - test

build-job:
  stage: build
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - target/debug/client
      - target/debug/server
      - target/debug/config

show-executable:
  stage: exec
  script:
    - echo " -----------------Executable-------------------------" 
    - ./builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable

runjob:
  stage: run
  before_script:
    - ifconfig
  script:
    - cargo run --bin server > server.log 2>&1 &
    - PID=$!
    - sleep 20
    - cargo run --bin client > client.log 2>&1 &
    - PIDS=$!
    - echo "Server PID: $PID"
    - echo "Client PID: $PIDS"
    - ps -a
    - kill -9 $PID
    - echo "Server killed"
    - kill -9 $PIDS
    - echo "Client killed"
    - ps -a
  artifacts:
    paths:
      - server.log
      - client.log

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test