stages:
  - build
  - run
  - test

build-job:
  stage: build
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - target/debug/client
      - target/debug/server
      - target/debug/config

run-applications:
  stage: run
  before_script:
    - ifconfig
  script:
    - ./test_server.sh & 
    - sleep 10
    - ./test_client.sh
  
test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test