stages:
  - build
  - exec
  - run
  - test

build-job:
  stage: build
  before_script:
    - touch builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable
    - chmod +x builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable 
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable

show-executable:
  stage: exec
  script:
    - echo " -----------------Executable-------------------------" 
    - ./builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable

run-server-job:
  stage: run
  before_script:
    - ifconfig
  script:
    - cargo run --bin server & 
    - sleep 10
    - cargo run --bin client

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test