stages:
  - build
  - run
  - test

build-job:
  stage: build
  image: rust:latest
  tags:
    - my-runner
  script:
    - cargo build --verbose

run-server-job:
  stage: run
  image: rust:latest
  script:
    - cargo run --bin server &
  tags:
    - my-runner
  artifacts:
    paths:
      - server

run-client-job:
  stage: run
  tags:
    - my-runner
  before_script:
    - sleep 2
  image: rust:latest
  script:
    - cargo run --bin client --verbose
  artifacts:
    paths:
      - client

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test