stages:
  - build
  - run
  - test

build-job:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

run-server-job:
  stage: run
  image: rust:latest
  before_script:
    - ifconfig
  script:
    - ( cargo run --bin server & ) && (PIDSERVER=$!) && ( cargo run --bin client & ) && (PIDCLIENT=$!) && (sleep 30 &) && (kill $PIDCLIENT ) && (kill $PIDSERVER)

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test