stages:
  - build
  - exec
  - run
  - test

build-job:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
  artifacts:
    path:
      - executable.sh

show-executable:
  stage: exec
  script:
    - echo " -----------------Executable-------------------------" 
    - ./executable.sh

run-server-job:
  stage: run
  image: rust:latest
  before_script:
    - ifconfig
  script:
    - (./test_server.sh & ./test_client.sh ) >test.log
  after_script:
    - echo "Output"
    - cat test.log

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test