image: rust:latest

stages:
  - build
  - run

variables:
  CARGO_TARGET_DIR: target

build:
  stage: build
  script:
    - echo "Building the project..."
    - cargo build --release

run_server:
  stage: run
  script:
    - echo "Running the server..."
    - cargo run --bin server &
    - sleep 5 # Wait for the server to start
    - echo "Executing virtualcancreation.sh from server..."
    - ./src/VirCanCreation.sh # Adjust the path as necessary

run_client:
  stage: run
  script:
    - echo "Running the client..."
    - cargo run --bin client