stages:
  - build
  - run
  - test

build-job:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

run-server-job:
  stage: run
  image: rust:latest
  script:
    - cargo run --bin server &
  artifacts:
    paths:
      - server
  
run-client-job:
  stage: run
  before_script:
    -sleep 2
  image: rust:latest
  script:
    - cargo run --bin client
  artifacts:
    paths:
      - client
  
test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test 