stages:
  - build
  - exec
  - run
  - test

build-job:
  stage: build
  script:
    - cargo build --verbose
  artifacts:
    paths:
      - target/debug/client
      - target/debug/server
      - target/debug/config

show-executable:
  stage: exec
  script:
    - echo " -----------------Executable-------------------------" 
    - ./builds/t3_FuHHD9/0/Aymen-Besbes/client_server_over_can/executable

run-server-job:
  stage: run
  before_script:
    - ifconfig
  script:
    - cargo run --bin server &
    - PID=$!
    - sleep 20
    - cargo run --bin client &
    - PIDS=$!
    - echo $PID
    - echo $PIDS
    - ps -a
    - kill -9 $PID
    - echo "client killed"
    - kill -9 $PIDS
    - echo "client server"
    - ps -a
    
test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test