stages:
  - build
  - run
  - test

build-job:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

run-server-job:
  stage: run
  image: rust:latest
  script:
    - cargo run --bin server
  needs: ["run-client-job"]

run-client-job:
  stage: run
  image: rust:latest
  script:
    - sleep 5
    - cargo run --bin client
  needs: ["run-server-job"]

test-job:
  stage: test
  image: rust:latest
  script:
    - cargo test

    
